#!/usr/bin/env bash
# This build file is executed by Sagoku Static Web App deployment
# when you configure your Sagoku Static Web App build script path to point here
# The container that executes this script will copy the result to S3 bucket sequoia-static

# set -e : tell script to exit as soon as any line in the bash script fails.
# set -x : prints each command that is going to be executed with a little plus.
set -ex

SRC_DIR=$1 # root folder of the workspace, /opt/git/workspace
BUILD_DIR=$2 # /mnt/deb-builds/${PACKAGE_NAME}-${VERSION}
PACKAGE_NAME=$3 # appName
VERSION=$4 # autogenerated timestamp
echo "Using package ${PACKAGE_NAME} and version ${VERSION}"
echo "Building ${PACKAGE_NAME} in ${BUILD_DIR}"

cd $SRC_DIR/
# Set up node and npm install libraries.
NODE_VERSION=v7.7.3
wget https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.xz
xz -dc node-${NODE_VERSION}-linux-x64.tar.xz | tar xf - -C /usr/local/

export PATH=$PATH:/usr/local/node-${NODE_VERSION}-linux-x64/bin

mkdir -p ${SRC_DIR}/build
npm install -g yarn
#npm install
yarn install

REACT_APP_SGK_ENVIRONMENT=$SGK_ENVIRONMENT yarn build

rsync -a ${SRC_DIR}/build/* ${BUILD_DIR}/
ls -la ${SRC_DIR}/build/
echo "Build script complete"
