export const POST_FEEDBACK = "POST_FEEDBACK";
export const POST_FEEDBACK_FULFILLED = "POST_FEEDBACK_FULFILLED";
export const POST_FEEDBACK_REJECTED = "POST_FEEDBACK_REJECTED";
export const PING = "PING";
export const PONG = "PONG";
