export const ADD_SECTION = "ADD_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
export const MOVE_SECTION_UP = "MOVE_SECTION_UP";
export const MOVE_SECTION_DOWN = "MOVE_SECTION_DOWN";
export const MODIFY_SECTION_NAME = "MODIFY_SECTION_NAME";
export const MODIFY_SECTION_NOTES = "MODIFY_SECTION_NOTES";

export const CHANGE_THESIS = "CHANGE_THESIS";

export const ADD_CITATIONS = "ADD_CITATIONS";
export const DELETE_CITATION = "DELETE_CITATION";
export const TOGGLE_CITATION_MODAL = "TOGGLE_CITATION_MODAL";
export const TOGGLE_DELETE_SECTION_MODAL = "TOGGLE_DELETE_SECTION_MODAL";

export const SELECT_LIST_ITEM = "SELECT_LIST_ITEM";
export const FETCH_LIST_ITEMS = "FETCH_LIST_ITEMS";
export const RECEIVE_LIST_ITEMS = "RECEIVE_LIST_ITEMS";
export const UNSELECT_LIST_ITEM = "UNSELECT_LIST_ITEM";
export const REQUEST_LIST_ITEMS = "REQUEST_LIST_ITEMS";
export const SELECT_ALL_LIST_ITEMS = "SELECT_ALL_LIST_ITEMS";
export const CLEAR_SELECTED_LIST_ITEMS = "CLEAR_SELECTED_LIST_ITEMS";

export const CHANGE_CITATION_FORMAT = "CHANGE_CITATION_FORMAT";
export const REQUEST_CITATION_FORMAT = "REQUEST_CITATION_FORMAT";
export const RECEIVE_CITATION_FORMAT = "RECEIVE_CITATION_FORMAT";

export const OUTLINE_SAVED = "OUTLINE_SAVED";
export const DOWNLOAD_OUTLINE = "DOWNLOAD_OUTLINE";
export const REQUEST_SAVE_AND_THEN_DOWNLOAD = "REQUEST_SAVE_AND_THEN_DOWNLOAD";
export const REQUEST_SAVE = "REQUEST_SAVE";

export const DIRTY_ACTIONS = [
    ADD_SECTION,
    CHANGE_THESIS,
    ADD_CITATIONS,
    DELETE_SECTION,
    DELETE_CITATION,
    MOVE_SECTION_UP,
    MOVE_SECTION_DOWN,
    MODIFY_SECTION_NAME,
    MODIFY_SECTION_NOTES,
    CHANGE_CITATION_FORMAT
];